'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class addnewchaptereditor

    '''<summary>
    '''pnlOuterWrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOuterWrap As Global.mojoPortal.Web.UI.OuterWrapperPanel

    '''<summary>
    '''ctop1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctop1 As Global.mojoPortal.Web.Controls.CornerRounderTop

    '''<summary>
    '''pnlInnerWrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInnerWrap As Global.mojoPortal.Web.UI.InnerWrapperPanel

    '''<summary>
    '''heading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents heading As Global.mojoPortal.Web.UI.HeadingControl

    '''<summary>
    '''pnlOuterBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOuterBody As Global.mojoPortal.Web.UI.OuterBodyPanel

    '''<summary>
    '''pnlInnerBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInnerBody As Global.mojoPortal.Web.UI.InnerBodyPanel

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''existingseriesdropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents existingseriesdropdown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''msg_existingseriesdropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msg_existingseriesdropdown As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''listlabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listlabel2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''existingchaptersdropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents existingchaptersdropdown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''msg_existingchaptersdropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msg_existingchaptersdropdown As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chooseseriesbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chooseseriesbutton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''backtodashboard2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents backtodashboard2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chaptername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chaptername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chapternameRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chapternameRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''datechaptercreated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datechaptercreated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ispublishedlabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ispublishedlabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ischapterpublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ischapterpublished As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''friendlyurllabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friendlyurllabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friendlyurllabellblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friendlyurllabellblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''friendlyurl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents friendlyurl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''spnUrlWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnUrlWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''checkurl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkurl As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''chaptertext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chaptertext As Global.mojoPortal.Web.Editor.EditorControl

    '''<summary>
    '''editchapterbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editchapterbutton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BacktoDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BacktoDashboard As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''divCleared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCleared As Global.mojoPortal.Web.UI.EmptyPanel

    '''<summary>
    '''cbottom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbottom1 As Global.mojoPortal.Web.Controls.CornerRounderBottom
End Class
