'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class addnewseries

    '''<summary>
    '''pnlOuterWrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOuterWrap As Global.mojoPortal.Web.UI.OuterWrapperPanel

    '''<summary>
    '''ctop1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctop1 As Global.mojoPortal.Web.Controls.CornerRounderTop

    '''<summary>
    '''pnlInnerWrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInnerWrap As Global.mojoPortal.Web.UI.InnerWrapperPanel

    '''<summary>
    '''heading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents heading As Global.mojoPortal.Web.UI.HeadingControl

    '''<summary>
    '''pnlOuterBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOuterBody As Global.mojoPortal.Web.UI.OuterBodyPanel

    '''<summary>
    '''pnlInnerBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInnerBody As Global.mojoPortal.Web.UI.InnerBodyPanel

    '''<summary>
    '''existingseriesdropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents existingseriesdropdown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''msg_existingseriesdropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msg_existingseriesdropdown As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''newserieslabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newserieslabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''addnewseriesname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addnewseriesname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''submitnewnseriesname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitnewnseriesname As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BacktoDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BacktoDashboard As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''divCleared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCleared As Global.mojoPortal.Web.UI.EmptyPanel

    '''<summary>
    '''cbottom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbottom1 As Global.mojoPortal.Web.Controls.CornerRounderBottom
End Class
